### ISSUE TITLE
atom.workspaceView is deprecated.

### ISSUE THREAD

**Issue by robballou** [unDemian/clipboard-history#12]
(via Atom's Deprecation Cop): atom.workspaceView is no longer available. In most cases you will not need the view. See the Workspace docs for alternatives: https://atom.io/docs/api/latest/Workspace. If you do need the view, please use `atom.views.getView(atom.workspace)`, which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
Object.activate (/Users/rballou/.atom/packages/clipboard-history/lib/clipboard-history.coffee:15:31)
```

**Comment by unDemian** [comment]
Fixed all the deprecation issues. Thanks
