### ISSUE TITLE
Breaks the copy line feature

### ISSUE THREAD

**Issue by capaj** [unDemian/clipboard-history#15]
When without this plugins I use ctrl+c I copy the whole line where cursor is into the clipboard. With this plugin, this is broken.
Tested on 0.187.0 with clipboard-history 0.6.3

**Comment by unDemian** [comment]
There is a setting to enable whole line copy. Go to Settings Tab -> Packages -> Search for clipboard-history and there is a checkbox for full line copy.
Thanks

**Comment by capaj** [comment]
@unDemian  yeah but maybe this setting should be on by default? I personally would not expect a default behaviour to change just by installing a plugin.

**Comment by unDemian** [comment]
You are right, I dont think it was by default in atom when I first created the plugin. I will enable it by default.

**Comment by unDemian** [comment]
This is fixed now. Thanks

**Comment by capaj** [comment]
@unDemian thank you
