### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [unDemian/clipboard-history#21]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.6.5`) of this package:

1. Open-ended transactions are deprecated. Use checkpoints instead.
1. Use TextEditor::selectLinesContainingCursors instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see what deprecations are being reported on this package.

See https://github.com/atom/atom/issues/6867 for more info.

**Comment by timohofmeijer** [comment]
:cry:

**Comment by unDemian** [comment]
This was fixed in 0.6.6
Thanks for you feedback.
