### ISSUE TITLE
Popup list isn't centered correctly,

### ISSUE THREAD

**Issue by kayone** [unDemian/clipboard-history#24]
![image](https://cloud.githubusercontent.com/assets/412280/9415574/288b6d7e-47f5-11e5-9fd4-344c3275213d.png)

preferably is should appear just like the fuzzy-search/command popup,

![image](https://cloud.githubusercontent.com/assets/412280/9415605/56215c76-47f5-11e5-94da-51e2d0db3edd.png)

**Comment by unDemian** [comment]
This is on purpose, with the next version the popup should be near the cursor. I don't like the top centered position :) Thanks for your feedback.
